CREATE TABLE CLIENTES (
    ID INTEGER NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    NOME_NORM VARCHAR(120) COMPUTED BY (UPPER(NOME)),
    EMAIL VARCHAR(120),
    ATIVO SMALLINT DEFAULT 1,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (ID);
CREATE UNIQUE INDEX UX_CLIENTES_EMAIL ON CLIENTES (EMAIL);
CREATE INDEX IX_CLIENTES_NOME ON CLIENTES (NOME);

CREATE TABLE PEDIDOS (
    ID INTEGER NOT NULL,
    CLIENTE_ID INTEGER NOT NULL,
    DATA_EMISSAO DATE NOT NULL,
    VALOR_TOTAL NUMERIC(15,2) DEFAULT 0,
    STATUS VARCHAR(20) DEFAULT 'ABERTO'
);

ALTER TABLE PEDIDOS ADD CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (ID);
CREATE INDEX IX_PEDIDOS_CLIENTE ON PEDIDOS (CLIENTE_ID);
CREATE INDEX IX_PEDIDOS_DATA_STATUS ON PEDIDOS (DATA_EMISSAO, STATUS);

CREATE TABLE ITENS_PEDIDO (
    ID INTEGER NOT NULL,
    PEDIDO_ID INTEGER NOT NULL,
    PRODUTO_ID INTEGER NOT NULL,
    QUANTIDADE NUMERIC(15,3) NOT NULL,
    VALOR_UNITARIO NUMERIC(15,2) NOT NULL,
    VALOR_TOTAL NUMERIC(15,2) NOT NULL
);

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT PK_ITENS_PEDIDO PRIMARY KEY (ID);
ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_ITENS_PEDIDO_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS (ID) ON DELETE CASCADE;
CREATE INDEX IX_ITENS_PEDIDO_PEDIDO ON ITENS_PEDIDO (PEDIDO_ID);
CREATE INDEX IX_ITENS_PEDIDO_PRODUTO ON ITENS_PEDIDO (PRODUTO_ID);

CREATE TABLE PRODUTOS (
    ID INTEGER NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    PRECO NUMERIC(15,2) NOT NULL,
    ATIVO SMALLINT DEFAULT 1
);

ALTER TABLE PRODUTOS ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID);
CREATE UNIQUE INDEX UX_PRODUTOS_NOME ON PRODUTOS (NOME);
