CREATE TABLE CLIENTES (
    ID INTEGER NOT NULL,
    NOME VARCHAR(100)
);

CREATE TABLE PEDIDOS (
    ID INTEGER NOT NULL,
    CLIENTE_ID INTEGER,
    VALOR NUMERIC(15,2)
);

ALTER TABLE PEDIDOS
    ADD CONSTRAINT FK_PEDIDOS_CLIENTE
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (ID);

CREATE INDEX IND_PEDIDOS_CLIENTE_A ON PEDIDOS (CLIENTE_ID);
CREATE INDEX IND_PEDIDOS_CLIENTE_B ON PEDIDOS (CLIENTE_ID);
