CREATE TABLE CLIENTES (
    ID INTEGER NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    NOME_NORM VARCHAR(120) COMPUTED BY (LOWER(NOME)),
    TIPO VARCHAR(10)
);

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (ID);
CREATE INDEX IX_CLIENTES_TIPO ON CLIENTES (TIPO);

CREATE TABLE PEDIDOS (
    ID INTEGER NOT NULL,
    CLIENTE_ID INTEGER,
    DATA_EMISSAO DATE,
    OBSERVACAO VARCHAR(255)
);

ALTER TABLE PEDIDOS ADD CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID);
CREATE INDEX IX_PEDIDOS_DATA ON PEDIDOS (DATA_EMISSAO);
CREATE INDEX IX_PEDIDOS_DATA_DUP ON PEDIDOS (DATA_EMISSAO);

CREATE TABLE ITENS_PEDIDO (
    ID INTEGER NOT NULL,
    PEDIDO_ID INTEGER,
    QUANTIDADE NUMERIC(15,2)
);

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT PK_ITENS_PEDIDO PRIMARY KEY (ID);
CREATE INDEX IX_ITENS_PEDIDO_QTD ON ITENS_PEDIDO (QUANTIDADE);

CREATE TABLE PAGAMENTOS (
    ID INTEGER NOT NULL,
    PEDIDO_ID INTEGER,
    VALOR NUMERIC(15,2)
);

ALTER TABLE PAGAMENTOS ADD CONSTRAINT PK_PAGAMENTOS PRIMARY KEY (ID);
