ALTER TABLE "CLIENTES" ADD "ATIVO" SMALLINT DEFAULT 1;
ALTER TABLE "CLIENTES" ADD "DATA_CADASTRO" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "CLIENTES" ADD "EMAIL" VARCHAR(120);
ALTER TABLE "CLIENTES" ALTER COLUMN "NOME" TYPE VARCHAR(120);
CREATE INDEX "IX_CLIENTES_NOME" ON "CLIENTES" ("NOME");
CREATE UNIQUE INDEX "UX_CLIENTES_EMAIL" ON "CLIENTES" ("EMAIL");
ALTER TABLE "ITENS_PEDIDO" ALTER COLUMN "PEDIDO_ID" SET NOT NULL;
ALTER TABLE "ITENS_PEDIDO" ADD "PRODUTO_ID" INTEGER NOT NULL;
ALTER TABLE "ITENS_PEDIDO" ALTER COLUMN "QUANTIDADE" TYPE NUMERIC(15,3);
ALTER TABLE "ITENS_PEDIDO" ALTER COLUMN "QUANTIDADE" SET NOT NULL;
ALTER TABLE "ITENS_PEDIDO" ADD "VALOR_TOTAL" NUMERIC(15,2) NOT NULL;
ALTER TABLE "ITENS_PEDIDO" ADD "VALOR_UNITARIO" NUMERIC(15,2) NOT NULL;
ALTER TABLE "ITENS_PEDIDO" ADD CONSTRAINT "FK_ITENS_PEDIDO_PEDIDO" FOREIGN KEY ("PEDIDO_ID") REFERENCES "PEDIDOS" ("ID") ON DELETE CASCADE;
CREATE INDEX "IX_ITENS_PEDIDO_PEDIDO" ON "ITENS_PEDIDO" ("PEDIDO_ID");
CREATE INDEX "IX_ITENS_PEDIDO_PRODUTO" ON "ITENS_PEDIDO" ("PRODUTO_ID");
ALTER TABLE "PEDIDOS" ALTER COLUMN "CLIENTE_ID" SET NOT NULL;
ALTER TABLE "PEDIDOS" ALTER COLUMN "DATA_EMISSAO" SET NOT NULL;
ALTER TABLE "PEDIDOS" ADD "STATUS" VARCHAR(20) DEFAULT 'ABERTO';
ALTER TABLE "PEDIDOS" ADD "VALOR_TOTAL" NUMERIC(15,2) DEFAULT 0;
ALTER TABLE "PEDIDOS" ADD CONSTRAINT "FK_PEDIDOS_CLIENTE" FOREIGN KEY ("CLIENTE_ID") REFERENCES "CLIENTES" ("ID");
CREATE INDEX "IX_PEDIDOS_CLIENTE" ON "PEDIDOS" ("CLIENTE_ID");
CREATE INDEX "IX_PEDIDOS_DATA_STATUS" ON "PEDIDOS" ("DATA_EMISSAO", "STATUS");
CREATE TABLE "PRODUTOS" (
    "ID" INTEGER NOT NULL,
    "NOME" VARCHAR(120) NOT NULL,
    "PRECO" NUMERIC(15,2) NOT NULL,
    "ATIVO" SMALLINT DEFAULT 1
);
ALTER TABLE "PRODUTOS" ADD CONSTRAINT "PK_PRODUTOS" PRIMARY KEY ("ID");
CREATE UNIQUE INDEX "UX_PRODUTOS_NOME" ON "PRODUTOS" ("NOME");
