-- Sample DDL intentionally containing multiple structural issues for analyzer showcase.

CREATE TABLE CLIENTES (
    ID INTEGER NOT NULL,
    NOME VARCHAR(100),
    TIPO_INVALIDO TYPE_999
);

CREATE TABLE PEDIDOS (
    ID INTEGER NOT NULL,
    CLIENTE_ID INTEGER,
    CLIENTE_ID_AUX INTEGER,
    VALOR NUMERIC(15,2),
    CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID_COLUNA_INEXISTENTE),
    CONSTRAINT FK_PEDIDOS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (ID),
    CONSTRAINT FK_PEDIDOS_CLIENTE_DUP FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (ID),
    CONSTRAINT FK_PEDIDOS_CARD FOREIGN KEY (CLIENTE_ID_AUX) REFERENCES CLIENTES (ID, NOME),
    CONSTRAINT FK_PEDIDOS_LOCAL_MISSING FOREIGN KEY (CLIENTE_INEXISTENTE) REFERENCES CLIENTES (ID),
    CONSTRAINT FK_PEDIDOS_REF_TABLE_MISSING FOREIGN KEY (CLIENTE_ID_AUX) REFERENCES CLIENTES_X (ID),
    CONSTRAINT FK_PEDIDOS_REF_COLUMN_MISSING FOREIGN KEY (CLIENTE_ID_AUX) REFERENCES CLIENTES (ID_X)
);

CREATE TABLE LOG_EVENTOS ();

CREATE TABLE ITENS_PEDIDO (
    ID INTEGER,
    PEDIDO_ID INTEGER,
    PRODUTO_ID INTEGER,
    CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS (ID)
);

CREATE INDEX IND_PEDIDOS_CLIENTE_A ON PEDIDOS (CLIENTE_ID);
CREATE INDEX IND_PEDIDOS_CLIENTE_B ON PEDIDOS (CLIENTE_ID);
CREATE INDEX IND_PEDIDOS_SEM_COLUNA ON PEDIDOS ( );
CREATE INDEX IND_PEDIDOS_COLUNA_INEXISTENTE ON PEDIDOS (CLIENTE_ID_NAO_EXISTE);
